# Generated by Django 2.0.1 on 2018-01-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('name_variants', models.TextField()),
                ('current_function', models.CharField(max_length=100)),
                ('previous_functions', models.TextField()),
                ('identification_string', models.CharField(max_length=8, unique=True)),
            ],
        ),
    ]
