# Generated by Django 2.0.1 on 2018-01-25 08:10

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politician',
            name='id',
        ),
        migrations.AlterField(
            model_name='politician',
            name='identification_string',
            field=models.CharField(default=application.models.make_id_string, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='politician',
            name='name_variants',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='previous_functions',
            field=models.TextField(blank=True),
        ),
    ]
