# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT depolitics.wsgi

runtime_config:
    python_version: 3

beta_settings:
    cloud_sql_instances: depolitics-org:us-central1:depolitics-org

handlers:
  - url: /static
    static_dir: static
    
  - url: .*
    script: depolitics.wsgi.application
    secure: always
# [END runtime]
