version: '3'

services:
  depolitics_db:
    image: postgres
  depolitics.org:
    # build: .
    image: caveljan/holocene-timestamp-app
    command: python3 manage.py runserver 0.0.0.0:8000
    expose:
      - 80
      - 443
    environment:
      VIRTUAL_HOST: depolitics.org
      LETSENCRYPT_HOST: depolitics.org
      LETSENCRYPT_EMAIL: caveljan@gmail.com
    volumes:
      - .:/code
    # ports:
    #   - "8000:8000"
    depends_on:
      - depolitics_db


networks:
  default:
    external:
      name: nginx-proxy